---
- name: Generate hosts file in localhost for all cvm instances
  hosts: localhost
  tasks:
    - name: Copy hosts file
      command: cp /etc/hosts hosts

    - name: Update ecs IPs in hosts file
      lineinfile:
        dest: hosts
        line: "{{ hostvars[item].qcloud.PublicIpAddresses[0] }} {{ item }}"
      with_list: "{{ groups['cvm'] }}"

    - name: print some messages
      debug: 
        msg: "Copy hosts to overwrite your /etc/hosts"

- name: Generate hosts file in all cvm instances
  hosts: cvm
  tasks:
    - name: Update ecs IPs in hosts file
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item].qcloud.PublicIpAddresses[0] }} {{ item }}"
      with_list: "{{ groups['cvm'] }}"

    - name: Update ecs private IPs in hosts file
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item].qcloud.PrivateIpAddresses[0] }} {{ item }}"
      with_list: "{{ groups['cvm'] }}"
