--- 
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
  - name: create work dir
    file:
      path: "{{ item }}"
      mode: 0755
      state: directory
    with_items:
      - /data0/src/
    tags: create_work_dir
