--- 
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
  - name: create /home/deploy
    file:
      path: /home/deploy
      mode: 0755
      state: directory
    tags: create_deploy_dir

  - name: create /home/backups
    file:
      path: /home/backups
      mode: 0755
      state: directory
    tags: create_backups_dir
