--- 
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
  - name: nginx install
    yum: state=latest name=nginx

  - name: make sure a service is running
    systemd: 
      state: started 
      name: nginx
    tags: nginx_service_running

  - name: enable service and ensure it is not masked
    systemd:
      name: nginx
      enabled: yes
      masked: no
    tags: nginx_service_start

  handlers:
    - name: restart nginx
      service: name=nginx enabled=yes state=restarted
      tags: restart_nginx
