---
- hosts: all
  remote_user: root
  sudo: yes
  gather_facts: false
  tasks:
  - name: install java-1.8.0-openjdk
    yum: state=latest name=java-1.8.0-openjdk
    tags: install_openjdk_1.8.0

  - name: rsysc openjdk_env.sh
    copy:
      src: files/{{ item }}
      dest: /data0/src/{{ item }}
      owner: root
      group: root
      mode: 0664
    with_items:
      - openjdk_env.sh
    tags: rsync_env_scripts
    
  - name: java env setup
    shell: sh /data0/src/openjdk_env.sh
    tags: config_openjdk_env
