---
- import_playbook: create_work_dir.yml

- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
  - name: dnsmasq install
    yum: name=dnsmasq state=latest

  - name: make sure a service is running
    systemd: state=started name=dnsmasq
    tags: start_service

  - name: enable service and ensure it is not masked
    systemd:
      name: dnsmasq
      enabled: yes
      masked: no
    tags: service_boot
