---
- hosts: all
  remote_user: root
  gather_facts: true
  vars:
    - harden_win_temp_dir: 'c:\Program Files\ansible'
    - harden_win_log_dir: 'c:\ProgramData\ansible\log'
  tasks:
  - name: RedHat os tools packages install
    include: "RedHat.yml"
    when:
      - ansible_os_family == "RedHat"

  - name: Ubuntu or Kali GNU/Linux or Debian tools packages install
    include: "Ubuntu.yml"
    when:
      - ansible_os_family == "Debian" or ansible_os_family == "Kali GNU/Linux"

  - name: Mac os tools packages install
    include: "MacOS.yml"
    when:
      - ansible_os_family == "Darwin"

  - name: Windows os tools packages install
    include: "Windows.yml"
    when:
      - ansible_os_family == "Windows"
