---
- import_playbook: create_work_dir.yml

- hosts: all
  remote_user: root
  sudo: yes
  gather_facts: true
  vars:
    terraform_version: terraform_0.11.10_linux_amd64.zip
    terraform_inventory_version: terraform-inventory_v0.7-pre_linux_amd64.zip
  tasks:
  - name: create /usr/local/terraform dir
    file:
      path: /usr/local/terraform/bin/
      mode: 0755
      state: directory
    tags: create_depe_dir

  - name: rsync app packages
    shell: cd /data0/src/ && \
           rsync -avz {{ REPO_IP }}::DATA/devops/packages/{{ item }} .
    with_items:
      - "{{ terraform_version }}"
      - "{{ terraform_inventory_version }}"
    tags: rsync_file

  - name: unzip app packages
    shell: cd /data0/src/ && unzip -o {{ item }} -d /usr/local/terraform/bin/
    with_items:
      - "{{ terraform_version }}"
      - "{{ terraform_inventory_version }}"
    tags: unzip_terraform

  - name: rsync terraform_env.sh
    copy:
      src: files/terraform/terraform_env.sh
      dest: /data0/src/terraform_env.sh
      owner: root
      group: root
      mode: 0755
    tags: rsync_env_scripts

  - name: terraform env setup
    shell: sh /data0/src/terraform_env.sh
    tags: config_terraform_env
