---
- import_playbook: create_work_dir.yml
- import_playbook: install_jdk.yml
- import_playbook: install_tools_packages.yml

- hosts: all
  remote_user: root
  gather_facts: true
  vars:
    - mycat_version: Mycat-server-1.6-RELEASE-20161028204710-linux.tar.gz
    - hostnames_file: "/etc/hosts"
    - ipnames:
      - { ip: '192.168.200.100', hostname: 'dn1' }
      - { ip: '192.168.200.101', hostname: 'dn2' }
      - { ip: '192.168.200.102', hostname: 'dn3' }
  tasks:
  - name: rsync {{ mycat_version }}
    shell: cd /data0/src/ && \
           rsync -avz {{ REPO_IP }}::DATA/devops/packages/{{ mycat_version }} .
    tags: rsync_packages

  - name: unzip app packages
    unarchive: 
      src: "/data0/src/{{ mycat_version }}"
      dest: /usr/local/
      remote_src: yes
    tags: unzip_app_packages

  - name: useradd mycat and other
    shell: useradd mycat; chown -R mycat.mycat /usr/local/mycat
    tags: other_setup

  - name: add ipnames to {{ hostnames_file }}
    lineinfile: 
      dest: "{{ hostnames_file }}"
      line: "{{ item.ip }} {{ item.hostname }}"
    with_items: 
      - "{{ ipnames }}"
    tags: add_ipnames

  - name: rsync /usr/local/mycat/conf/schema.xml
    template:
      src: "files/mycat/{{ item }}.j2"
      dest: "/usr/local/mycat/conf/{{ item }}"
      owner: mycat
      group: mycat
      mode: 0777
      backup: yes
    with_items:
      - schema.xml
      - server.xml
    tags: rsync_config
