--- 
- hosts: all
  remote_user: root
  gather_facts: false
  vars:
    - http_user: supervisor 
    - http_passwd: 09348c20a019be0318387c08df7a783d
  tasks:
  - name: supervisor install
    yum: state=latest name=supervisor
    tags: install_supervisor_packages

  - name: rsync supervisord.conf
    template:
      src: files/supervisord.conf.j2
      dest: /etc/supervisord.conf
      owner: root
      group: root
      mode: 0664
      backup: yes
    notify: restart supervisord
    tags: rsync_supervisor_conf

  - name: make sure a service is running
    systemd: 
      state: started 
      name: supervisord
    tags: supervisord_service_running

  - name: enable service and ensure it is not masked
    systemd:
      name: supervisord
      enabled: yes
      masked: no
    tags: supervisor_service_start

  handlers:
    - name: restart supervisord
      service: name=supervisord enabled=yes state=restarted
      tags: restart_supervisord
