---
- import_playbook: create_work_dir.yml

- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
  - name: download ambari.repo
    get_url:
      url: http://qcloud-cdn.xxx.cn/loveworld/ambari.repo
      dest: /etc/yum.repos.d/
    tags: ambari_repo
