--- 
- import_playbook: create_work_dir.yml
- import_playbook: install_jdk.yml
- import_playbook: install_nginx.yml

- hosts: all
  remote_user: root
  gather_facts: false
  vars:
    - teamcity_version: "TeamCity-2018.1.1.tar.gz"
  tasks:
  - name: download {{ teamcity_version }}
    shell: cd /data0/src/ && \
           rsync -avz {{ REPO_IP }}::DATA/devops/packages/{{ teamcity_version }} .
    tags: download_app_packages

  - name: unzip app packages
    unarchive: 
      src: "/data0/src/{{ teamcity_version }}"
      dest: /usr/local/
      remote_src: yes
    tags: unzip_app_packages

  - name: print messages
    debug:
      msg: '/usr/local/TeamCity/bin/runAll.sh start'
    tags: print_messages
