---
- import_playbook: create_work_dir.yml
- import_playbook: install_tools_packages.yml

- hosts: all
  remote_user: root
  gather_facts: false
  vars:
    - consul_version: 1.2.2
    - consul_server_port: 8300
    - consul_rpc_port: 8400
    - consul_http_port: 8500
    - consul_dns_port: 8600
    - consul_ip_bind: "{{ ansible_default_ipv4.address }}"
    - consul_client_bind: "0.0.0.0"

    - consul_home: "/data0/consul"
    - consul_datadir: "{{ consul_home }}/data"
    - consul_confdir: "{{ consul_home }}/conf"
    - consul_dc: "dc1"
    - consul_loglevel: "INFO"
    - consul_server: true
    - consul_ui: true
    - consul_node_name: "{{ ansible_hostname }}"

    - consul_bootstrap_expect: 1
    - consul_bootstrap: false
    - consul_dev: false
    - consul_encrypt: false
    - consul_start_join: []
  tasks:
  - name: download consul_{{ consul_version }}_linux_amd64.zip
    get_url: url=https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip dest=/data0/src/
    tags: download_app_packages

  - name: unzip app packages
    unarchive: src=/data0/src/consul_{{ consul_version }}_linux_amd64.zip dest=/data0/src/
    tags: unzip_app_packages

  - name: install consul
    shell: install /data0/src/consul /usr/local/bin/
    tags: install_consul

  - name: mkdir data and log dir
    file:
      path: /data0/consul/{{ item }}
      owner: root
      group: root
      mode: 0755
      state: directory
    with_items:
      - data
      - conf
      - logs
    tags: create_app_work_dir

  - name: configure consul.conf file.
    template:
      dest: "{{ consul_confdir }}/basic_config.json"
      mode: 0644
      src: files/consul/basic_config.json.j2
      owner: root
      group: root
    tags: rsync_consul_conf

  - name: print messages
    debug:
      msg: "{{ item }}"
    with_items:
      - "consul agent --server --bind=192.168.200.101 --data-dir=/data0/consule/data -bootstrap-expect=1 -node=nginx-lb -client 0.0.0.0 -ui"
    tags: print_minikube_cmd
