--- 
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
  - name: rsync composer
    copy:
      src: files/composer
      dest: /usr/bin/composer
      owner: root
      group: root
      mode: 0755
