---
- import_playbook: create_work_dir.yml
- import_playbook: install_jdk.yml

- hosts: all
  remote_user: root
  gather_facts: true
  vars:
    - cloudera_version: '5.15.1'
    - mysql_connector_java_version: '8.0.11'
    - install_type: local   # download|local
  tasks:
  - name: create user cloudera-scm
    shell: useradd --system \
                   --home=/opt/cm-5.15.1/run/cloudera-scm-server/ \
                   --no-create-home \
                   --shell=/bin/false \
                   --comment "Cloudera SCM User" cloudera-scm
    tags: add_user_cloudera

  - name: other setup
    shell: echo never > /sys/kernel/mm/transparent_hugepage/defrag \
           echo never > /sys/kernel/mm/transparent_hugepage/enabled \
           echo 10 > /proc/sys/vm/swappiness
    tags: other_setup

  - name: other setup
   
  - name: boot settings /etc/rc.local    
    lineinfile:      
      path: /etc/rc.local     
      line: "\n# cloudera setup at {{ ansible_date_time.date }} by madongsheng\n
                 echo never > /sys/kernel/mm/transparent_hugepage/defrag\n
                 echo never > /sys/kernel/mm/transparent_hugepage/enabled"    
    tags: boot_settings

  - name: vm.swappiness
    lineinfile:
      path: /etc/sysctl.d/99-sysctl.conf
      line: "vm.swappiness = 10"
    tags: boot_settings

  - name: rsysc cloudera-manager.repo
    copy:
      src: files/cloudera/cloudera-manager.repo
      dest: /etc/yum.repos.d/cloudera-manager.repo
      owner: root
      group: root
      mode: 0644
    tags: rsync_cloudera_repo
