---
- hosts: all
  become: true
  become_user: root
  remote_user: root
  gather_facts: true
  vars:
    jenkins_cli_cmd: "/var/cache/jenkins/war/WEB-INF/jenkins-cli.jar"
  tasks:
  - name: create jenkins jobs
    shell: java -jar {{ jenkins_cli_cmd }} -s http://localhost:8080 create-job {{ item }} < {{ item }}.xml
    with_items:
      - job1
    tags: import_jenkins_repo_key

