---
# Tasks specific for Ubuntu systems

- name: Ubuntu or Kali GNU/Linux or Debian os tools packages install
  apt: 
    name: "{{ item }}"
    state: latest 
  with_items:
    - bzip2
    - curl
    - diffutils
    - dos2unix
    - gawk
    - gcc
    - git
    - grep
    - gzip
    - make
    - zip
    - htop
    - httping
    - iftop
    - iotop
    - less
    - lftp
    - nfs-common
    - nmap
    - openssl
    - p7zip
    - pv
    - pwgen
    - ranger
    - rar
    - rsync
    - smbclient
    - software-properties-common
    - sshfs
    - sshpass
    - tar
    - tmux
    - trash-cli
    - tig
    - tree
    - unzip
    - vim
    - wget
    - whois
    - python
    - yum
    - net-tools
  tags: install_tools_packages
