---
# Tasks specific for Windows OS systems

- name: create ansible directories
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ harden_win_temp_dir }}"
    - "{{ harden_win_log_dir }}"
  ignore_errors: true
  tags: create_work_dir

- name: copy install chocolatey powershell scripts
  win_copy:
    src: files/windows/install_chocolatey.ps1
    dest: "{{ harden_win_temp_dir }}/"
  tags: copy_install_chocolatey_scripts

- name: run install_chocolatey.ps1
  win_shell: "Set-ExecutionPolicy Bypass -Scope Process -Force; 
              iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
  tags: run_install_chocolatey_scripts

- name: windows os tools packages install
  win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items:
    # - 7zip
    - googlechrome
    - winrar
    - notepadplusplus.install
    - openssh
    - curl
    - wget
    - nmap
    - python2
    - rsync
    # - beyondcompare
    # - pycharm-community
    # - wireshark
    # - foxitreader
    # - filezilla
    # - cygwin
    # - cyg-get
    # - git.install
    # - teamviewer
    # - keepass.install
    # - vim
    # - atom
    # - sublimetext3
    # - python3
    # - firefoxesr
    # - tortoisesvn
  tags: install_tools_packages
